name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      name: ${{ steps.vars.outputs.name }}
      tag: ${{ steps.vars.outputs.tag }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to ACR
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Set image values
      id: vars
      run: |
        TAG=$(date +%s)
        NAME=devansha-optimus/productsstoreonkubernetes/my-image-name
        echo "name=$NAME" >> $GITHUB_OUTPUT
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        docker build MvcApp -f MvcApp/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ steps.vars.outputs.name }}:${{ steps.vars.outputs.tag }}

    - name: Push Docker image to ACR
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ steps.vars.outputs.name }}:${{ steps.vars.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

    - name: Replace image placeholders in deployment file
      run: |
        sed -e "s|__DOCKER_REPOSITORY__|${{ secrets.ACR_LOGIN_SERVER }}|" \
            -e "s|__IMAGE_NAME__|${{ needs.build.outputs.name }}|" \
            -e "s|__IMAGE_TAG__|${{ needs.build.outputs.tag }}|" \
            kubernetes/mvc-deployment.azure.yaml > kubernetes/mvc-deployment.final.yaml

    - name: Deploy all Kubernetes manifests
      run: |
        kubectl apply -f kubernetes/mssql-configmap.yaml
        kubectl apply -f kubernetes/mssql-secret.yaml
        kubectl apply -f kubernetes/mssql-pv.azure.yaml
        kubectl apply -f kubernetes/mssql-deployment.yaml
        kubectl apply -f kubernetes/mvc-deployment.final.yaml
