deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Set up kubeconfig
    run: |
      mkdir -p $HOME/.kube
      echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

  - name: Prepare image tag
    id: image
    run: echo "IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/devansha-optimus/productsstoreonkubernetes/${{ needs.build.outputs.tag }}" >> $GITHUB_ENV

  - name: Replace image in deployment file
    run: |
      sed "s|__IMAGE__|${IMAGE}|" kubernetes/mvc-deployment.azure.yaml > kubernetes/mvc-deployment.final.yaml

  - name: Deploy all Kubernetes manifests
    run: |
      kubectl apply -f kubernetes/mssql-configmap.yaml
      kubectl apply -f kubernetes/mssql-secret.yaml
      kubectl apply -f kubernetes/mssql-pv.azure.yaml
      kubectl apply -f kubernetes/mssql-deployment.yaml
      kubectl apply -f kubernetes/mvc-deployment.final.yaml
